### PR TITLE
Updated NGA GEOPackage core from 2.0.1 to 6.5.0

### PR DESCRIPTION
**Pull request by PWRxPSYCHO**
#1707 
#1684 
#1706 

Looking to update the NGA-Geopackage libraries within OSMDroid to the latest versions.

### CODE REVIEW

**Comment by eclectice** [comment]
Because **GeoPackage** now supports ***DocumentFile*** natively, we may be able to provide support for ***DocumentFile*** as an alternative to ***File*** (polymorphs methods to support both classes) so Geopackage files can be opened from the shared storage with respect to scoped storage introduction since Android 10+.

**Review by monsieurtanuki — APPROVED** [review]
Looks good to me @PWRxPSYCHO!

**Comment by PWRxPSYCHO** [comment]
> Because **GeoPackage** now supports _**DocumentFile**_ natively, we may be able to provide support for _**DocumentFile**_ as an alternative to _**File**_ (polymorphs methods to support both classes) so Geopackage files can be opened from the shared storage with respect to scoped storage introduction since Android 10+.
> 
> Even, to make it more flexible, we can simply use the _**GeoPackage**_ class instead of the _**File**_ class. A Geopackage file can have multiple tiles tables storing different tile maps. With a single tile source approach, we can separately handle each tile table with a separate **GeoPackageMapTileModuleProvider()**.
> 
> ```java
> Map<String, MapTileModuleProviderBase> providers = new LinkedHashMap<>();
> //tiles object stores info about each geopackage file data (database, tile table, current tile table active state)
> //so, we can granularly control its data that we want to manipulate
> //key is database:table string format
> String key = String.join(":", tiles.getDatabase(), tiles.getName());
> //handle one geopackage
> GeoPackage geoPackage = geoPackageViewModel.getGeoPackage(tiles.getDatabase());
> GeoPackageProvider geoPackageProvider = new GeoPackageProvider(geoPackage, activity);
> 
> if (tileOverlays.get(key) == null) {
>     TilesOverlay tilesOverlay = new TilesOverlay(geoPackageProvider, activity); //with default MapTileProviderBase
>     tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
>     tilesOverlay.setLoadingLineColor(Color.TRANSPARENT);
>     tilesOverlay.setLoadingDrawable(null);
> 
>     tileOverlays.put(key, tilesOverlay);
> }
> 
> //...
> if (!mapView.getOverlayManager().overlays().contains(tileOverlays.get(key))) {
>     mapView.getOverlayManager().add(tileOverlays.get(key));
>     mapView.setDrawingCacheBackgroundColor(Color.TRANSPARENT);
>     mapView.setBackgroundColor(Color.TRANSPARENT);
> }
> 
> //this geopackage may have multiple tile tables
> GeoPackageMapTileModuleProvider provider = geoPackageProvider.geoPackageMapTileModuleProvider();
> providers.put(key, provider);
> GeoPackageMapTileModuleProvider provider = (GeoPackageMapTileModuleProvider) providers.get(key);
> List<GeopackageRasterTileSource> tileSources = provider
>         .getTileSources(tiles.getDatabase(), tiles.getName(), tiles.isActive());
> tileSources.forEach((tileSource) -> {
>     if (tileSource != null) {
>         String tileSourceName = ((GeopackageRasterTileSource) tileSource).name();
>         //...
>         final MapTileFileStorageProviderBase cacheProvider =
>                 MapTileProviderBasic.getMapTileFileStorageProviderBase(simpleRegisterReceiver, tileSource, tileWriter);
>         providers.put(String.join("-", key, "cacheProvider"), cacheProvider);
>         //...
>         mapView.setTileSource(tileSource);
>         mapView.zoomToBoundingBox(((GeopackageRasterTileSource) tileSource).getBounds(), true);
>         mapView.getController().setZoom(((GeopackageRasterTileSource) tileSource).getMinimumZoomLevel()*1.0);
>     }
> });
> String[] providerNames = new String[providers.size()];
> int i = 0;
> for (Map.Entry<String, MapTileModuleProviderBase> entry : providers.entrySet()) {
> 	if (entry.getKey() != null && entry.getValue() != null) {
> 		providerNames[i++] = String.format("%s (%s)", entry.getKey(), entry.getValue().getClass().getSimpleName());
> 	}
> }
> 
> MapTileProviderArray obj = new MapTileProviderArray(tileSource, new SimpleRegisterReceiver(activity), providerArray);
> mapView.setTileProvider(obj);
> ```
> 
> This improvement is to limit _**GeoPackageProvider()**_ to a single _**GeoPackage**_ file so that we may control its tile source(s) more precisely with the required tileprovider(s) to manage a separate tile cache. It will be very simple to control the tile source hide/unhide feature (which is currently missing).
> 
> From
> 
> ```java
> public GeoPackageProvider(final IRegisterReceiver pRegisterReceiver,
>                               final INetworkAvailablityCheck aNetworkAvailablityCheck, final ITileSource pTileSource,
>                               final Context pContext, final IFilesystemCache cacheWriter, File[] databases)
> ```
> 
> to
> 
> ```java
> public GeoPackageProvider(final IRegisterReceiver pRegisterReceiver,
>                                  final INetworkAvailablityCheck aNetworkAvailablityCheck, final ITileSource pTileSource,
>                                  final Context pContext, final IFilesystemCache cacheWriter, GeoPackage geoPackage)
> ```
> 
> From
> 
> ```java
> public GeoPackageMapTileModuleProvider(File[] pFile,
>                                            final Context context, IFilesystemCache cache)
> ```
> 
> to
> 
> ```java
> public GeoPackageMapTileModuleProvider(final Context context, IFilesystemCache cache, GeoPackage geoPackage)
> ```
> 
> This is my version to idealize the above proposal. I've also hacked a way to control the range of zoom levels allowed on the tile source of each tile table based on the data from the GeoPackage file itself in the `getMapTile()` method rather than relying on the `getMaximumZoomLevel()` method. The latter's original method has a global effect: if there are multiple GeoPackage files loaded, the first one loaded will restrict the max zoom level allowed in the _**MapView**_ which is not desired. The same global effect occurs with the min zoom level of the original `getMinimumZoomLevel()` method.
> GeoPackageProvider
> GeoPackageMapTileModuleProvider
> GeopackageRasterTileSource
> 
> Discussions on my approach can be found here: [#1709 (comment)](https://github.com/osmdroid/osmdroid/issues/1709#issuecomment-1217772054)
> 
> Next support should be able to tell whether a table in a GeoPackage file is a features-based (vector type), a tiles-based (raster type), or feature tiles.

@eclectice Are these changes something that will be added to OSMDroid in the next release? Or is this a suggestion for developers who wish to use this feature going forward?

**Comment by PWRxPSYCHO** [comment]
@monsieurtanuki The CI looks like it is failing for an API version. Should I address that? Or could that be a breaking change for the application as a whole?

**Comment by monsieurtanuki** [comment]
> The CI looks like it is failing for an API version. Should I address that? Or could that be a breaking change for the application as a whole?

That does look like a breaking change.
Given that this could impact only the geopackage package (in its own `build.gradle`), and assuming that your PR is really worth it, we could upgrade only the geopackage package to sdk `32`.
Or, maybe you're able to identify what is causing this "min sdk 32" error - if it's something unimportant we can get rid of it.
Actually, I don't know very much about those things. @spyhunter99?

**Comment by eclectice** [comment]
@PWRxPSYCHO I suggest it as a proposal to be implemented once your change has been successfully committed, as I was unable to push my change owing to an unknown OsmDroid build issue with Gradle-Fury last time. I'm also unfamiliar with the Git tool.

On minimum SDK version, there is a note regarding Android platform support 
> Starting with AGP 7.3.0-beta05, the highest supported minimum SDK version is 33 (you can use minSdk = 33). The minimum SDK represents the minimum version of Android that your app can run on and is set in the app-level build.gradle file.

https://developer.android.com/studio/releases/gradle-plugin#android-platform-support

**Comment by monsieurtanuki** [comment]
> Starting with AGP 7.3.0-beta05

We don't need to go that high, do we?

**Comment by eclectice** [comment]
> > Starting with AGP 7.3.0-beta05
> 
> We don't need to go that high, do we?

My current AGP 7.3.0 build (which I will upgrade soon) generated this lint error demanding minSDKversion 24. https://issuetracker.google.com/issues/219091668?hl=id

**Comment by monsieurtanuki** [comment]
> My current AGP 7.3.0 build (which I will update this info soon) generated this lint error demanding minSDKversion 24.

That would be problematic for my Lollipop smartphone (21).

**Comment by eclectice** [comment]
> Latest CI build issue is related to this: [j256/ormlite-android#141](https://github.com/j256/ormlite-android/issues/141)
> 
> The compileSDK bump is no longer required

It is just a variable but it is not applied in the `android {}` entry

**Comment by eclectice** [comment]
> Latest CI build issue is related to this: [j256/ormlite-android#141](https://github.com/j256/ormlite-android/issues/141)
> 
> The compileSDK bump is no longer required

This is how I solved dependency duplicates between libraries that use different versions, and how I implemented my local version of OsmDroid Geopackage API support without using the same class package names. For example, I created ***SafGeoPackageProvider*** as a replacement for OsmDroid ***GeoPackageProvider*** version so that I could use the most recent GeoPackage API version.

```gradle
    api 'mil.nga.geopackage:geopackage-android:6.6.0'
    implementation('org.osmdroid:osmdroid-geopackage:6.1.14') {
        exclude group: 'org.osmdroid.gpkg'
        exclude module: 'ormlite-core'
        exclude group: 'com.j256.ormlite'
    }
```

**Comment by PWRxPSYCHO** [comment]
Last issue seems to be on the DocumentFile

There are 2 different versions being used. Android.x 1.0.1 & android support: 28.0.0

**Comment by eclectice** [comment]
> > Latest CI build issue is related to this: [j256/ormlite-android#141](https://github.com/j256/ormlite-android/issues/141)
> > The compileSDK bump is no longer required
> 
> It is just a variable but it is not applied in the `android {}` entry

Hmm, ***compileSdkVersion*** is still required in the `android {}` section since AGP complains about it if missing during the build.

**Comment by PWRxPSYCHO** [comment]
> > > Latest CI build issue is related to this: [j256/ormlite-android#141](https://github.com/j256/ormlite-android/issues/141)
> > > The compileSDK bump is no longer required
> > 
> > 
> > It is just a variable but it is not applied in the `android {}` entry
> 
> Hmm, _**compileSdkVersion**_ is still required in the `android {}` section since AGP complains about it if missing during the build.

If you checkout the CI run here: https://github.com/ScriptTactics/osmdroid/actions/runs/3244600273/jobs/5320984386#step:5:327

You'll see that it's clashing with the document file issue. Android-Support brings in version 28.0.0 while the NGA-Geopackage-Android brings in Androidx which uses version 1.0.1.

I am also running CI on my newest PR: #1856 -> 
https://github.com/ScriptTactics/osmdroid/actions/runs/3245757323/jobs/5323696698

This has all the changes in from this PR and the other PR. (Removing all android-support libraries and updating to Androidx) and there does not seem to be any issues about dependencies or duplicates

**Comment by eclectice** [comment]
Because of changes in the GeoPackage API since v2.0.1, this WIKI must be updated.
https://github.com/osmdroid/osmdroid/wiki/Geopackage-Support

**Comment by spyhunter99** [comment]
merged, feel free to update the wiki

**Pull request merged**
