### PR TITLE
feature/#1294_2 - new MapView.setMapCenterOffset method

### PR DESCRIPTION
**Pull request by monsieurtanuki**
The map center used to be projected into the screen center.
Now we have a possible offset from the screen center; default offset is [0, 0].

New class:
* `SampleMapCenterOffset`: demo about the new `MapView.setMapCenterOffset` method - demo that can be reached at "More Samples / Events / Animate To with Map Center Offset"

Impacted classes:
* `MapView`: created `int` members `mMapCenterOffsetX` and `mMapCenterOffsetY` with getters and a common setter; used it when constructing a new related `Projection`
* `Projection`: created `final int` members `mMapCenterOffsetX` and `mMapCenterOffsetY`; added these parameters to constructors; impacted accordingly methods `getScreenCenterX` and `getScreenCenterY`; gently refactored
* `SampleFactory`: added the new `SampleMapCenterOffset` demo
* `SampleMapSnapshot`: impacted the use of a `Projection` constructor

### CODE REVIEW

**Comment by PaoloDozio** [comment]
When do you think this added feature will be available in the baseline?

**Comment by pasniak** [comment]
ProjectionTest.java is missing offsets 0, 0

**Comment by pasniak** [comment]
After I fixed the build, the change works great, I tested on emu and tablet with a compass-driven-orientation.  Haven't implemented yet switching between offset and no offset.

**Comment by monsieurtanuki** [comment]
Oh, ProjectionTest, of course.

You didn't mention it before: what do you expect as a transition between different offsets? I guess something like should work:
````java
// from (offsetX, offsetY) to (0, 0)
GeoPoint g = mapview.getCenter;
mapview.setMapCenterOffset(0, 0); // no invalidate
mapview.setExpectedCenter(g, -offsetX, -offsetY); // supposed a transparent transition
mapview.animateTo(g); // smooth animation
````

**Comment by spyhunter99** [comment]
this looks good to me, just fix the merge conflict.

**Pull request merged**
