### PR TITLE
Travis CI Integration

### PR DESCRIPTION
**Pull request by ZKjellberg**
Since this project has integration tests which should be managed for future commits, adopting Travis CI could help alleviate some future issues.

I created this branch to test automatic builds using Travis CI but I am having issues.

Here is the page for the Travis builds attempted: https://travis-ci.org/ZKjellberg/osmdroid

It is currently failing on [line 2060: nexus.codehaus.org: Name or service not known](https://travis-ci.org/ZKjellberg/osmdroid#L2060). Also please note my .travis.yml config as I may need to tweak this.

If I could have some assistance troubleshooting this, it could be a worthwhile addition to the project as it will also test future pull requests.

### CODE REVIEW

**Comment by ZKjellberg** [comment]
Quick updates on this problem. Trying to navigate through the maven process, but can't seem to track down what is causing this.

1. Codehaus's services have been terminated and is now simply a website.
2. I cannot find a single reference to codehaus in any of the pom.xml files.

Reviewing the pom.xml, I am wondering if somehow a plugin like **android-maven-plugin** could be causing an issue? Considering this can run locally, I don't see why it would.

**Comment by spyhunter99** [comment]
You'll need the android sdk, the maven android sdk deployer, deploy that,
the start an emulator, the build osmdroid, then stop the emulator

On Tue, Dec 22, 2015 at 5:04 AM, Zachary Kjellberg <notifications@github.com

**Comment by ZKjellberg** [comment]
Travis CI supports Android Maven builds. In the [.travis.yml](https://github.com/ZKjellberg/osmdroid/blob/travis/.travis.yml) file I specified all dependencies that I am aware osmdroid uses. (It looks to resolve the dependencies without issue)[https://travis-ci.org/ZKjellberg/osmdroid] but when it executes the build for the OSM Android it fails on [line 2060: nexus.codehaus.org: Name or service not known](https://travis-ci.org/ZKjellberg/osmdroid#L2060).

I see in the (android-maven-plugin changelog)[https://github.com/simpligility/android-maven-plugin/blob/master/src/site/asciidoc/changelog.adoc] mention of resolving **Fix continuous integration(use Travis Android support and enable/update ITs)** which may be related to this problem? I doubt it since that seems to be an internal issue.

I now realize the codehaus error was just a **[WARNING]** and the actual error is resolving the Android target, which is the reason for your reply. The strange part, is I see in the logs
```
Downloading SDK Platform Android 6.0, API 23, revision 1
Installed SDK Platform Android 6.0, API 23, revision 1
Done. 1 package installed.
```
That matches our requirement of 6.0_r1. I need to learn more on how Travis CI works and see how to tweak the config to resolve this.

**Comment by spyhunter99** [comment]
https://travis-ci.org/ZKjellberg/osmdroid#L2078

this is the real error message. cannot find android:android.jar

On Tue, Dec 22, 2015 at 7:31 AM, Zachary Kjellberg <notifications@github.com

**Comment by ZKjellberg** [comment]
The 6.0_r1 I was referring to was part of that message. I don't understand why it'd fail if earlier it shows that it was properly installed.

**Comment by spyhunter99** [comment]
I don't see any indication that it was installed. Where do you see that?

On Tue, Dec 22, 2015 at 7:35 AM, Zachary Kjellberg <notifications@github.com

**Comment by ZKjellberg** [comment]
[Line 270](https://travis-ci.org/ZKjellberg/osmdroid#L270)

```
Installing Archives:
Preparing to install archives
Downloading SDK Platform Android 6.0, API 23, revision 1
Installing SDK Platform Android 6.0, API 23, revision 1
Unzipping SDK Platform Android 6.0, API 23, revision 1 (20%)
Unzipping SDK Platform Android 6.0, API 23, revision 1 (97%)
Installed SDK Platform Android 6.0, API 23, revision 1
Done. 1 package installed.
```

**Comment by spyhunter99** [comment]
need the maven android sdk deployer and mvn install -fn

On Tue, Dec 22, 2015 at 7:42 AM, Zachary Kjellberg <notifications@github.com

**Comment by spyhunter99** [comment]
can we have it clone the maven android sdk deployer in the script too?

**Pull request merged**
