### PR TITLE
Bug/#335 fix for a whole lot of memory leaks

### PR DESCRIPTION
**Pull request by spyhunter99**
This is a large commit (sorry!) that resolves a great deal of memory leaks. It's tested by running a slightly altered version of the instrumentation tests which loops for 100 iterations per sample fragment. If it doesnt crash on api 8 or api 10 devices (which has max heap of 25 MB) then we're in good shape. @MKergall may want to take a look at the changes for FolderOverlay and a few minor changes to Marker.

### CODE REVIEW

**Comment by MKergall** [comment]
Huge work. 
onDetach should also be added to Polygon and Polyline overlays, and to MinimapOverlay.

**Comment by spyhunter99** [comment]
Great catch

**Comment by spyhunter99** [comment]
long story short, nice quite ready to merge yet. I did add the detach methods for polyline and polygon. I also had to modify the IRegisterReceiver class to have a destroy method. I then found another slow leaker that was making the test process unstable over longer durations. I did add leak canary, ACRA and some code to dump hrpof files to find the error. Eventually I found a slow leak using the hprof file and MAT, ArrayAdapter in the FragmentSamples. It may be a bug in the API8 codebase.

**Comment by spyhunter99** [comment]
Turns out it wasn't an android bug, just a matter of poor documentation with list view fragments.

**Comment by spyhunter99** [comment]
MinimapOverlay will be covered by the TilesOverlay that it inherits from. Polyline and polygon were added

**Comment by spyhunter99** [comment]
yay! finally got ci to pass, any more suggestions @MKergall ?

**Comment by spyhunter99** [comment]
whoops, didn't mean to merge this, too late now i guess

**Pull request merged**
