### PR TITLE
Fixed gradle build error for support:compatibility 

### PR DESCRIPTION
**Pull request by ZKjellberg**
Current project features a build error as it is unable to resolve **support:compatibility** in the **OpenStreetMapViewer\build.gradle**. This error is referenced in issue #194.

> Error:(32, 13) Failed to resolve: android.support:compatibility-v4:23+

This is resolved by replacing the dependency:
> compile 'android.support:compatibility-v4:23+'

with

> compile 'com.android.support:support-v4:23+'

### CODE REVIEW

**Comment by johnnynotsolucky** [comment]
It should be possible to remove the dependency altogether as osmdroid handles all its own API conditions. 

The project builds without the dependency, but that's as far as I've tested it.

**Comment by spyhunter99** [comment]
@johnnynotsolucky it is required for the example app. When removing it from the maven build, it fails. Also fails with 'gradle clean build'

**Comment by spyhunter99** [comment]
Zach, wouldn't it be better to use 'buildToolsVersion=23+'? that would reduce our need to maintain these files everytime google decides to push an update

**Comment by ZKjellberg** [comment]
@johnnynotsolucky As @spyhunter99 has stated, if the user does a clean build, the dependency is still required. For example, the OpenStreetMapViewer module's **MapActivity extends FragmentActivity** from this support library. I see it as still necessary to change this gradle dependency as the original does not appear to exist and this allows building.

@spyhunter99 I actually did not intend to push up those changes yet for building. I should have branched and made a seperate pull request to acknowledge the cleanup, but forgot pull requests automatically pull updates. (Slightly rusty on my git, relearning bad behavior.) As for your suggestion to use **buildToolsVersion=23+**,  Android Studio does not seem able to accept this usage. I recognize it is a hassle to maintain the minor updates, but figure it would be worthy to tweak every so often with minor maintenance.

**Pull request merged**
