### PR TITLE
Feature/#906 ESRI ShapeFile reader + Bounds checks on drawing lines, polygons and markers

### PR DESCRIPTION
**Pull request by spyhunter99**
New module, ESRI Shape Reader. This converts shape file contents into polygons with the associated metadata attached to the infowindow popup. This is actually the smallest of the changes on this branch.

The large changes is optimizations to Polyline, Polygon, Marker, and Itemized Icon Overlay. As suggested by @MKergall in #770, this uses the bounding box check for those mentioned classes in the on draw method. If there is no overlap of the bounds of the overlay with the view's bounds, then skip the draw cycle.

Finally, assuming the line or polygon is within bounds, the point reduction algorithm is ran before drawing. At numerically low zoom levels, this usually reduces small scale polygons down to a triangle and it becomes more and more accurate the further in your zoom.

Impacts:
 - Bounds check: At numerically high zoom levels with a hundreds of geographically dispersed polygons, this has a huge performance boost (HUGE).
 - Point reduction: This has a noticeable impact at numerically low zoom levels
 - Polygons now have a "minimum zoom" level setting to prevent drawing a very low zoom levels. Default is 0 of course but it can be set to bypass drawing if needed for certain applications

Current open issues
 - Bounds check with info window. When the item scrolls out of view, the info window appears to cling to the edge of the screen. I did attempt to auto hide it but ran into some issues with it. I'm not sure what "right" looks like here.
 - When looking at the world at zoom <= 3, the bounds checks are skipped entirely due to world replication issues and no way to check if there are multiple worlds or not.

How to test
 - see #906, there's a download link for a shape file for country borders. Unzip it and copy the contents of the zip to somewhere on your device.
 - Open the app, more samples, Data, Shape File Import, hit the ... button, "Import a shape file"
 - then select the .shp file from the zip contents

### CODE REVIEW

**Comment by spyhunter99** [comment]
yup forgot i used an unpublished github project and built it locally
https://github.com/iryndin/jdbf/issues/11

**Comment by spyhunter99** [comment]
image

**Comment by spyhunter99** [comment]
image

**Comment by spyhunter99** [comment]
comparing the screen shots, looks like there are some polygons that are not rendered at the zoom level present. I'm thinking point reduction should be off by default

**Comment by monsieurtanuki** [comment]
> point reduction should be off by default

@spyhunter99 Rather than setting point reduction off by default, wouldn't that make sense to:
* set it on by default
* in case the point reduction doesn't display anything, use a new alternate and very stupid downgraded mode - like a `Polyline` between topLeft and bottomRight?

**Comment by MKergall** [comment]
For infowindow boundingbox check: 
A simple solution is to increase the  bounding box by a ratio in all directions. Maybe half the size: north += height*0.5

(More or less what is done with tiles)

**Comment by MKergall** [comment]
This will also solve similar issues on polylines with huge width, and big marker icons.

**Comment by spyhunter99** [comment]
@monsieurtanuki what i'm seeing is a complex polygon being reduced to just a very small triangle. Also point reduction is not applied to holes currently.

@MKergall good idea i'll see if i can work this in

**Comment by monsieurtanuki** [comment]
@spyhunter99 My assumption was that users prefer a very lousy approximation (that displays something worth zooming in on) (which may look like an ink stain) than no polygon at all on some high zoom levels.
Regarding its accuracy, I agree that it's not very relevant, but we're talking about polygons to be drawn on a very small pixel rectangle, right? I can't say what's better, I'm not a regular polygon user.

**Comment by spyhunter99** [comment]
more sample data https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas

**Comment by spyhunter99** [comment]
perhaps @monsieurtanuki can take a look at this if time allows. i think for polygons and polylines, we should run a point reducing algorithm against the points with zoom is less than 4 or so. using this branch, thew new sample and the linked shape file, draw speeds are less than 1 frame a second. there are tons of overlays and they are all hundreds of points each so naturally some performance issues are expected, however it can probably be better.

at one point, this branch had the point reducer setup built in, but since then theres been quite a bit of work has been done on polyline and polygon and this code is moot now. perhaps this would be better as a separate issue

**Comment by monsieurtanuki** [comment]
@spyhunter99 I guess at least you should separate the ESRI Shapefile Reader code from the Polygon rendering part, and merge the ESRI part.

Then it would be time to open a new issue about Polygon rendering, which would include overlapping, point reduction, minimum zoom level, and a target (like "fast polygon rendering with those inputs data and this zoom level").

**Comment by spyhunter99** [comment]
the biggest change here is that may impact other overlays and existing capabilities are the following

- polygon and polyline - with setPoints and addPoint will now auto set the bounding box the overlay
- folder overlay - with add/remove, the bounds of the overlay is calculated based all child overlays
- marker - bounds is now set to the point of the object
- itemized icon overlay - no changes
- default overlay manager - the bounds is compared with the current view before calling the draw method. it will only be called if the overlay is within, consumes, or overlaps the bounds.

non-impacts

- a new library for reading shape files. it can read plan shapes and metadata files. if metadata is available, all available data is appended to the title and/or description of the converted shape.
- not all shape file formats are supported, such as 3d shapes.
- the code in this library, and the dependency are asf/mit compatible. no gpl issues

since this branch was opened over a year ago, most of the pr is merged related

after merging, the wiki will be updated with further usage instructions

**Pull request merged**
