### PR TITLE
Smooth tile garbage collection, with new SQL index

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New classes:
* `GarbageCollector`: running a task smoothly and asynchronously, only one execution at the same time
* `GarbageCollectorTest`: unit test class related to `GarbageCollector`

Impacted class:
* `SqlTileWriter`: included index creation inside `runCleanupOperation` and one-by-one tile removal; replaced `runCleanupOperation` calls to garbage collection calls

### CODE REVIEW

**Comment by InI4** [comment]
Questions:
1. What is in the expiry column? If it is a timestamp, shouldn't this be sorted ascending instead of descending?
2. Couldn't at least the select for tiles be batched in the sense, that several are selected at once? The deletion itself could still be one by one ..

**Comment by monsieurtanuki** [comment]
Both remarks are correct, though the impact is light:
* the "ORDER BY" should be "ASC" instead of "DESC"
* we could retrieve the N eldest records (like, 10) and perform the same kind of loop

I'll fix that today.
Beyond that, do you agree with the mechanism?

**Comment by InI4** [comment]
1. Well, the order by would have deleted the freshest tiles, wouldn't it? This is more important.
2. Mechanism is cool, I am looking very much forward to it and hope, index creation will not kill us.
3. When I think of to my own little app, I'd actually even give a time limit, for example 4 weeks, and would delete tiles which are older than 4 weeks without the need of a storage bottleneck .. But this is a new feature ;-)

**Comment by monsieurtanuki** [comment]
> Well, the order by would have deleted the freshest tiles, wouldn't it? This is more important.

It's not that important as in the `SELECT` I already restricted to the _expired_ tiles: I wasn't deleting the youngest tiles, but the youngest _expired_ tiles. Anyway, I'm fixing it.

> Mechanism is cool, I am looking very much forward to it and hope, index creation will not kill us.

In the worst case, the index creation will happen only once. But we should put the index creation not only in the `gc` (for the old apps) but also just after the table creation (for newcomers).

**Comment by monsieurtanuki** [comment]
It should be better now.

About creating the index at table creation too, I don't see any elegant way to do it. And the index is meaningful only in the context of `gc` anyway. I guess we can survive without that feature.

**Comment by InI4** [comment]
Index creation table creation would have one advantage: It would be very fast, since the table is empty.

**Comment by monsieurtanuki** [comment]
The index creation will definitely be faster at table creation time.
Today I'll add a lousy "if count(*)=0 create index" statement just after the "create table if exists".
In the meanwhile any test of the tile garbage collection is welcomed.

**Comment by monsieurtanuki** [comment]
Just found and PR'ed an elegant SQL index creation timing.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Help needed. Doesn't seem to be able to compile, fails with that kind of log:
````
* What went wrong:
Could not resolve all dependencies for configuration ':osmdroid-server-jdk:compileClasspath'.
> Could not determine artifacts for org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016
   > Could not get resource 'https://jcenter.bintray.com/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit'.
      > Could not HEAD 'https://jcenter.bintray.com/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit'. Received status code 502 from server: Bad Gateway
````
Is the answer: "it's just a bad luck error, try later" or is there something we can fix on the osmdroid side?

**Comment by shiroyagi** [comment]
Looks nice, particularly your SQL.  A few thoughts:

1. Would it be worth putting a sleep (eg. 200ms) in your runCleanupOperation() loops?  This will reduce the load on the system and give other higher priority tasks a chance to run (eg. loading a tile from cache).
2. I would still reduce `lastSizeCheck + 300000`: small and often is definitely better (or at least make it tunable)
3. Is it worth checking `db_file.length()` in the loop in case additional tiles are added concurrently?
4. Possibly have the loop always running whilst the map is visible with a longer sleep (eg. 5s) to increase the separation of the cleanup from user interaction (less sure about this).

**Comment by monsieurtanuki** [comment]
@shiroyagi I totally agree with 1 and 2.

About 3: for different reasons we cannot rely 100% on db length anyway (the db file doesn't shrink automatically, if we delete a table record the corresponding index record are deleted as well, and the table record is slightly bigger than just the tile blob). Therefore I think we should apply the Pareto principle and admit the current algorithm is good enough.

About 4: I find elegant to run the gc only when we save tiles, and in offline mode I think it makes sense to keep expired tiles rather than deleting them and displaying nothing. And that offline specificity would have do be dealt with, which would make the code less readable.

About 5: if for some reason the db file shrinks very slowly we will delete much more records than needed, including not expired ones.

I'll work on 1 and 2 by the end of the week.

**Comment by shiroyagi** [comment]
Given the uncertain size on disk have you thought about `SQLiteDatabase.setMaximumSize()` and calling gc() in response to `SQLiteFullException`?

**Comment by spyhunter99** [comment]
I'll have a look at it

**Comment by monsieurtanuki** [comment]
@shiroyagi What should be done when `SQLiteFullException` is caught? I don't know, there's nothing functionally obvious.
For instance, imagine the user-defined database limit is 600Mb, and so far there are 400Mb in the db. And 500Mb left on the disk.
And then I download 500Mb of MP3 on my disk: the disk is full.
What could we expect of osmdroid:
* removal of expired and unexpired tiles - down to which Mb limit? why would osmdroid tiles be considered as less important than the recent MP3 files?
* display of a `Toast`?
* display of a "Cleanup Yes/No" alert dialog?

I think that whatever is related to `SQLiteFullException` should be part of a new issue: the current issue only deals with on-the-fly `gc`.
I guess we should let the developer catch `SQLiteFullException` and decide what to do with it in the context of his own app.
What I can do in the current issue is adding parameters to the tile removal process:
* total tile size to be deleted (now: db file length - max expected db size)
* bulk size (now: 20)
* sleep duration between bulk actions (now: 0)
* including unexpired tiles or not (now: false)

**Comment by shiroyagi** [comment]
Yes, that all that sounds good and anything more can be done elsewhere.

My expectation was that the Android API would provide a better way to understand the size the database when some of it may be cached in memory.  I would hope `SQLiteFullException` relates to `setMaximumSize()` and that something else filling the disk would result in `SQLiteDiskIOException` or some other exception but this would need testing.

Even if it behaves as I hope `SQLiteFullException` is not ideal as by this point new rows are being rejected (a soft limit or `getSize()` would be better).  Still it may be the best we can do and after catching one I would add the rejected new tile transaction to an asynchronous queue to be completed after something else is removed (gc to the trim size):
`SQLiteDatabase.setMaximumSize(Configuration.getInstance().getTileFileSystemCacheMaxBytes())`

**Comment by monsieurtanuki** [comment]
@spyhunter99 Seems to be OK now.

**Comment by monsieurtanuki** [comment]
Just PR'ed a version of `runCleanupOperation` with more flexibility and configuration default parameters.

**Comment by monsieurtanuki** [comment]
@shiroyagi Does this PR eventually solve #965? Can we merge it?

**Pull request merged**
