### PR TITLE
Limited the number of tested fragments in "connectedCheck"

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Because of numerous _time out_ issues with "connectedCheck", we decided to restrict the tested fragments to the ones with an overriden `BaseSampleFragment.runTestProcedures` method. And method `BaseSampleFragment.skipOnCiTests` also reflects that.

### CODE REVIEW

**Comment by monsieurtanuki** [comment]
Doesn't seem to work. The low verbosity in the travis log of command `travis_wait 60 ./gradlew clean install connectedCheck` doesn't help...

**Comment by monsieurtanuki** [comment]
@spyhunter99 Could you please have a look at the travis logs? I have the funny impression that even without fragments being tested, the "connectedCheck" step lasted about 20 minutes (cf. [1018.1](https://api.travis-ci.org/v3/job/318012809/log.txt), [1018.2](https://api.travis-ci.org/v3/job/318012810/log.txt), [1018.3](https://api.travis-ci.org/v3/job/318012811/log.txt)).

**Comment by spyhunter99** [comment]
There's a fair amount of time waiting for the emulator to be created and then started. Not too much we can do about it

**Comment by monsieurtanuki** [comment]
@spyhunter99 Actually I didn't expect you to merge those commits that fast! It was some kind of experimental thing, trying to have a clearer idea of what's going on.

What I can say so far from the logs:
* without the "connectedCheck" step, the travis thing lasts about 17 minutes
* the "connectedCheck" step without any test to run lasts about 19 minutes (emulator related init)
* both `Bug445Caching` and `Bug512CacheManagerWp` step last about 1 minute
* I don't know about steps `Bug512Marker`, `MapInAViewPagerFragment` and `SampleOsmPath`, but I suspect one of them to be the ugly duckling (probably `SampleOsmPath` with its forever loops)

What is merged now:
* there's a "connectedCheck" step
* this step lasts 20 minutes and runs only `Bug512CacheManagerWp`

What we could do next:
1. temporarily remove the "connectedCheck" step and merge, so that anybody will see its PR travis last 20 minutes less and probably always succeed
1. in parallel, try to optimize each of the 5 test fragments - optimize meaning either writing faster code or moving code into regular JUnit test
1. in a dedicated work branch, put the "connectedCheck" step back and try to understand what's going on with the last 3 test fragments. The goal being to eventually merge "connectedCheck" back into master, with relevant/optimized test fragments.

What do you think of it?

**Pull request merged**
