### PR TITLE
Feature/#736

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New class `ZoomButtonsOverlay` to be used in `MapView` instead of `ZoomButtonsController`.

### CODE REVIEW

**Comment by spyhunter99** [comment]
i like it, just waiting on travis

**Comment by MKergall** [comment]
Well, I'm not so enthousiastic... The design, why not. But the API... 
I want to set it (center,bottom) as it was before: why is it so complex and unclear? 
Previous button was vanishing automatically when no pan - this feature disapeared.

**Comment by spyhunter99** [comment]
hmm i see your point, it is significantly different than the old setup

**Comment by spyhunter99** [comment]
moving this conversation to https://github.com/osmdroid/osmdroid/issues/823

**Pull request merged**
