### PR TITLE
#1723 should address the latlon grid painting issue and then some

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by spyhunter99** [comment]
@mikebravoyes does this work for you?

**Comment by mikebravoyes** [comment]
@spyhunter99 
That looks perfect. When will the new version 6.1.11 be on the market?

**Comment by spyhunter99** [comment]
tonight

**Comment by mikebravoyes** [comment]
@spyhunter99 
Thanks for the update, but there is still problem. My code is
```
LatLonGridlineOverlay2 gridOverlay = new LatLonGridlineOverlay2();
gridOverlay.setTextStyle(Paint.Style.FILL_AND_STROKE);
```
`.setTextStyle(...)` crashes with an **InvocationTargetException** - with the "detailMessage":
_No virtual method setTextStyle(Landroid/graphics/Paint$Style;)V in class Lorg/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay2; or its super classes (declaration of 'org.osmdroid.views.overlay.gridlines.LatLonGridlineOverlay2' appears in /data/data/net.braun_home.sensorrecording.pro/code_cache/.overlay/base.apk/classes.dex)_

When I copy the code of LatLonGridlineOverlay2 to an own file (let's say LatLonGridlineOverlay3) and adapt the package, the class and constructor name accordingly, then everything works fine with:
```
LatLonGridlineOverlay3 gridOverlay = new LatLonGridlineOverlay3();
gridOverlay.setTextStyle(Paint.Style.FILL_AND_STROKE);
```
The code in both cases is identical, but when I invoke the method of the osmdroid library, it crashes. Any idea, why this happens?

**Comment by spyhunter99** [comment]
Are you using version 6.1.11?

**Comment by mikebravoyes** [comment]
Yes, of course. In the previous version 6.1.10, the method 
`public void setTextStyle(Paint.Style paint) { mTextPaint.setStyle(paint);}` 
did not yet exist.

**Comment by mikebravoyes** [comment]
@spyhunter99 
Good news! I did another try today with `LatLonGridlineOverlay2` and - to my surprise - now it works. No idea what went wrong yesterday. I didn't change anything, except a new start of Android Studio. Maybe there was an old code fragment somewhere in the cache, which was removed by the restart.

Anyway, now everything is OK. Thanks again for the modification.

**Pull request merged**
