### PR TITLE
feature/#725 - computing the `LinearRing` clip area limits

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Impacted classes:
* `LinearRing`: removed clip area limits constants; created methods `setClipArea` in order to set the most relevant clip area according to the current `MapView`
* `Polygon`: used new method `LinearRing.setClipArea(MapView)`
* `Polyline`: used new method `LinearRing.setClipArea(MapView)`

### CODE REVIEW

**Comment by pasniak** [comment]
Does this commit fix the behavior below ?
osmdroid 2017-11-15 06-13

**Comment by monsieurtanuki** [comment]
@pasniak That's exactly what it is supposed to fix.

**Comment by spyhunter99** [comment]
test results:
- HW acceleration off
   - line, perfect
   - polygon, ran into an issue a strange issue with panning at max zoom, video coming
   - polygon with holes, no other issues
- HW accerlation ON
  - line, perfect
  - polygon, ran into one case where the drawing got weird, video coming
  - polygon with holes, no other issues

**Comment by spyhunter99** [comment]
video links added. not sure if this issue is the good cause of this PR or not

**Comment by monsieurtanuki** [comment]
I just managed to reproduce the first video (hw acceleration off).
I'll have a look at this bug.

**Comment by monsieurtanuki** [comment]
(supposedly) fixed.
For the record, it was a side effect on "how to clip a segment into a clip area where there's no intersection at all between them".
@spyhunter99 I could not reproduce the second bug before I started to work on the first one, but I did reproduce it while I was fixing. Then fixed it. Not very clear I guess: in short, I fixed both bugs you uploaded a video for.

**Comment by spyhunter99** [comment]
@monsieurtanuki ok i'll test it this weekend.

**Comment by spyhunter99** [comment]
test results:
- HW acceleration off
   - line, perfect
   - polygon, perfect!
   - polygon with holes, perfect!
- HW accerlation ON
  - line, perfect
  - polygon, perfect!
  - polygon perfect!
  - one note is that zoom out animation is a bit slow but i'll gladly merge as is

thanks @monsieurtanuki !

**Pull request merged**
