### PR TITLE
Feature/#787 Repetition Modes

### PR DESCRIPTION
**Pull request by Maradox**
`MapView` now supports the configuration of the repetition in the horizontal and vertical direction:
* `setHorizontalMapRepetitionEnabled(boolean)`
* `setVerticalMapRepetitionEnabled(boolean)`

Issue: https://github.com/osmdroid/osmdroid/issues/787

### CODE REVIEW

**Comment by Maradox** [comment]
1. If preferred, I could change the API of the `MapView` to use an `Enum` for the repetition modes.

2. I am currently not sure if the adjustment in `LinearRing` is correct (at the location of the TODO).

**Comment by spyhunter99** [comment]
Great work! After some quick testing, this appears to be correct with one exception. When panning the map, (vertical off, horizontal on), the algorithm that determines where the draw overlays needs to be adjusted. Currently the plotted points/lines/polygons scroll all the way off screen. The previous behavior (vertical on, horizontal on) this can be viewed easily by zooming to 0, then panning the map around. As the line/polygon/point pans off screen, it will get redrawn on the most appropriate world.

**Comment by spyhunter99** [comment]
@Maradox looking at linear ring now, that's the problem area

**Comment by spyhunter99** [comment]
might have fixed it, probably not as efficient as it could be though..

**Comment by spyhunter99** [comment]
@MKergall  how's this?

**Comment by MKergall** [comment]
Not tried yet, but it seems good! Absolutely no need for an Enum. 
If you merge on master, I will test. 

@Maradox You seem reluctant to change default behaviour, and default vertical replication to false. Is it just to respect compatibility, or do you have another reason?

**Comment by spyhunter99** [comment]
@MKergall merged, it's all you

**Comment by Maradox** [comment]
@MKergall No, just for compatibly reasons.

**Pull request merged**
