### PR TITLE
Feature/#640 floating point zoom levels

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by spyhunter99** [comment]
so giant change set but really an awesome bit of functionality
For new methods, @monsieurtanuki can we add the `@since v5.6.5` text so there's at least some indication of when it was added?

**Comment by spyhunter99** [comment]
actually this change, along with the other changes you've proposed, would probably put use closer to a v5.7 or perhaps even 6.0 release

**Comment by spyhunter99** [comment]
yikes i looked at the merge issues, will need @monsieurtanuki 's help with that one

**Comment by monsieurtanuki** [comment]
@spyhunter99 I just delivered a new merged version of MapTileProviderBase, to be considered as the new master.
Regardless of the conflicts I added trying to merge the code ;)

[MapTileProviderBase.java.txt](https://github.com/osmdroid/osmdroid/files/1185092/MapTileProviderBase.java.txt)

**Comment by monsieurtanuki** [comment]
I've just double-checked that "[feature/#640](https://github.com/osmdroid/osmdroid/pull/647)" versions are the good ones for
* `MapTileProviderArray` on its only conflict
* `MapTileProviderBase` on its 9 conflicts

**Comment by monsieurtanuki** [comment]
@spyhunter99 How to merge:
* for `MapTileProviderArray`, take the common code and all the "feature/640" code, ignore the master code
* for `MapTileProviderBase`, take the common code and all the "feature/640" code, ignore the master code
* for `SqlTileWriter`, take the common code and either the "feature/640" or the "master" code, both are identical except for spaces in javadoc

**Comment by spyhunter99** [comment]
@monsieurtanuki for future reference, on your box, you want to switch to the branch, say 'feature/640', then merge master into that branch. Resolve the conflicts, then commit the merge. SourceTree makes this painless on windows or macos. unfortunately linux has few options. I've pushed the merged changes to osmdroid/feature/#640

just tested everything and it's passing all the tests on this end.  should be able to merge after travis does its thing

**Pull request closed without merging**
