### PR TITLE
using batchmode and adding updated flag for Maven builds

### PR DESCRIPTION
**Pull request by mosabua**
I tried building locally and I did not get the compile problems you see on travis. So at least theoretically this should work

-B removes the log lines for KB download stuff
-U forces to check in upstream repo for artifacts

hth

### CODE REVIEW

**Comment by spyhunter99** [comment]
sweet! much appreciated

**Comment by neilboyd** [comment]
When I look at the Travis log it's full of errors, but they're just ignored because of -fn
Or am I missing something?

**Comment by mosabua** [comment]
Which log are you looking at specifically? And yes -fn ignores errors.

**Comment by mosabua** [comment]
Also... you have to merge and try and see if it works.

**Comment by mosabua** [comment]
Haha .. I just noticed you have branch build with travis and this branch passed.. and I did take out the repeated maven invocations. Let me check more in the log.

**Comment by mosabua** [comment]
Looking at the travis log I still see compile problems. I do NOT get them locally.

**Comment by mosabua** [comment]
You should see if you can manually run the SDK deployer locally and then an osmdroid build. That works for me.

**Comment by neilboyd** [comment]
I've been trying it a few times, and it seems to sometimes work and sometimes not.  I'm not sure what's different between the times it works and the times it doesn't.
But surely I shouldn't need to clean maven-android-sdk-deployer every time?
And shouldn't osmdroid work without `-fn -B -U`? Or at least without `-fn`?

**Comment by mosabua** [comment]
Well.. thats what I am saying. It works without -fn for me just fine. Reproducibly..

**Comment by spyhunter99** [comment]
the current travis file, clones the maven-sdk-deployer, then install -fn. Then builds osmdroid.

On my box, if i wipe out the .m2 repo, the problem is reproduced. Travis builds are essentially new VMs with every build and thus an empty local .m2 repo.

**Comment by mosabua** [comment]
Let me try with a clean setup ..

**Comment by neilboyd** [comment]
Thank you for helping Manfred, I very much appreciate it :)

Please could you explain your thinking behind these changes that you made to .travis.yml:

For maven-android-sdk-deployer:
Why clean?  On the Travis server it's already a new box, and locally it takes forever.
Why -U?

For osmdroid:
Why -fn?  We want it to just pass without errors.
Why -U?  This causes it to get other osmdroid dependencies from Maven Central, whereas we should be building against our local version.

Sorry if I'm just not understanding Maven properly ;)

**Comment by neilboyd** [comment]
When I said "other osmdroid dependencies", I mean, for example, this:

> [INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/osmdroid/osmdroid-android/5.1-SNAPSHOT/osmdroid-android-5.1-20160117.193112-7.aar

**Comment by mosabua** [comment]
clean is probably not necessary

-fn not either - it just causes it to keep running even if it fails

download from snapshots.. that looks like a bug in your project setup.

**Comment by spyhunter99** [comment]
yup still an issue.
https://travis-ci.org/osmdroid/osmdroid/builds/103978076 this is without -fn

**Comment by neilboyd** [comment]
Hx'm x

**Pull request merged**
