### PR TITLE
bug/#1005 - SqlTileWriter now uses a static database, in order to avoid locks

### PR DESCRIPTION
**Pull request by monsieurtanuki**
A direct impact is that the app must be restarted in order to have a database path change taken into account.

Impacted class:
* `SqlTileWriter`: `db_file` and `db` are now `static`; added a `static` lock used in the constructor; removed everything in `onDetach` as nobody should close a `static` database

### CODE REVIEW

**Comment by monsieurtanuki** [comment]
@spyhunter99 The idea of a `static` database could help fix the bookmark crashes #998

**Comment by spyhunter99** [comment]
the danger with this is permissions or if the storage location is external storage and it's unmounted. There won't be a way to refresh the database connection

**Comment by monsieurtanuki** [comment]
> There won't be a way to refresh the database connection

A solution might be to be more aggressive about `Exception`s inside `SqlTileWriter`: if we catch something that says "OK you tried to insert a record but you don't even have a usable database", then we can reset the `db` to `null`.
And if instead of a direct access to `db` inside `SqlTileWriter` we use some kind of `getDb` method that checks first if `db` is null and sets it (like in the `synchronized(mLock)` part) if necessary, we'll have the best of both worlds: a database without locks, and a database that can be refreshed at any time (even more flexible that before this PR).
@spyhunter99 What do you think of this?

**Comment by monsieurtanuki** [comment]
Just implemented in `SqlTileWriter`:
* a `getDb` method to be used systematically in order to get the database (and to reconnect if necessary)
* a `refreshDb` method in order to explicitly ask for a database reconnection
* more subtile `catch`es of `SQLiteException` in order to automatically refresh the database when relevant

@spyhunter99 Does it cover all your requirements?

**Comment by secaw** [comment]
@monsieurtanuki Without testing yet - looks like the perfect solution. What if we extend `SqlTileWriter`, will it also use the single instance?

**Comment by monsieurtanuki** [comment]
@secaw I'm not sure it will work if you extend `SqlTileWriter`; perhaps by just overriding `getDb`. I'm not a _design pattern_ expert, but maybe using a _factory_ would help.
Do you currently extend `SqlTileWriter`? Because there are currently 10 places in the code where `new SqlTileWriter()` is used: how do you manage that?

**Comment by secaw** [comment]
Ok, thanks - I just use an extended `SqlTileWriter` for custom cache scanning and cleaning. Had no conflicts so far, so probably doesn't matter anyways...

**Comment by monsieurtanuki** [comment]
@secaw Thinking again about it that should be OK.
What is important is the singleton'ed database, not the `SqlTileWriter` instances - there are many, but with the same database. It should be the same for the classes that extend `SqlTileWriter`, as long as they use `SqlTileWriter.getDb`.

**Comment by secaw** [comment]
@monsieurtanuki Thanks for clarification, that's what I reckoned too.

**Comment by monsieurtanuki** [comment]
@InI4 @secaw During splash screen you can now run:
````java
new DuringSplashScreen().runDuringSplashScreen();
````

**Comment by spyhunter99** [comment]
I'm OK with this

**Pull request merged**
