### PR TITLE
feature/#790: map scale merged into floating point zoom

### PR DESCRIPTION
**Pull request by monsieurtanuki**
This is just a teaser, there are things to fix. For instance, the pinch gesture center is not yet taking into consideration (zooming in or out scrolls the map to the bottom right).
All comments are welcomed.

Impacted classes:
* `CompassOverlay`: used the new `Canvas` related `Matrix` methods of `Projection`
* `CopyrightOverlay`: used the new `Canvas` related `Matrix` methods of `Projection`
* `LinearRing`: integrated the fact that there's no map scale anymore / should be considered as equal to 1
* `MapController`
  * feature-related: edited `zoomToFixing` and `onAnimationUpdate`; simplified `onAnimationEnd`
  * refactoring: removed members `mZoomInAnimation` and `mZoomOutAnimation`; simplified methods `zoomIn`, `zoomInFixing`, `zoomOut`, `zoomOutFixing`
* `MapView`
  * feature-related: removed members `ZOOM_SENSITIVITY`, `ZOOM_LOG_BASE_INV`, `mTargetZoomLevel` and `mMultiTouchScale`; deprecated methods `getZoomLevel(final boolean aPending)`, `zoomIn`, `zoomOut` and `getMapScale`; simplified `canZoomIn` and `canZoomOut`; optimized `dispatchDraw` using the new `Canvas` related `Matrix` methods of `Projection`; created new methods `startAnimation`, `setMultiTouchScale` and new member `mStartAnimationZoom`; impacted pinch gesture methods `getPositionAndScale`, `selectObject` and `setPositionAndScale`
  * refactoring: removed members `sMotionEventTransformMethod` and `mMercatorPoint`; deprecated methods `getLatitudeSpan`, `getLongitudeSpan` and `getBoundingBoxE6`; simplified method `rotateTouchEvent`
* `MinimapOverlay`: removed the "display only when not animating" restriction
* `Projection`
  * feature-related: removed member `float mMultiTouchScale`; removed parameter `pScale` from constructor; removed scale operations from matrices; optimized the computation of `mCurrentCenter`; added methods `save` and `restore` that apply the matrices to canvas only if necessary.
  * refactoring: renamed member as `mWrapEnabled`; simplified the initialization of `mScreenRectProjection`; added generic method `apply` that apply a `Matrix` to a `Point`
* `ScaleBarOverlay`: used the new `Canvas` related `Matrix` methods of `Projection`
* `ZoomButtonsOverlay`: used the new `Canvas` related `Matrix` methods of `Projection`; restricted the zoom action to a `ACTION_UP` event

### CODE REVIEW

**Comment by secaw** [comment]
WOW, this is fantastic! Working absolutely flawlessly as far as I can see. In debug mode I still get the 'scaled' tags written on the tiles, but that's probably only a logging issue. Thanks!

**Comment by monsieurtanuki** [comment]
@secaw Thank you for your comment! I'm about to deliver the last fixes (regarding the map centering); I'm glad I finally understood the way the pinch gesture is supposed to work.
For the record, the idea is that:
1. at the start of the pinch gesture, the pixel in the middle of your 2 fingers is kept
1. this pixel corresponds to geo coordinates
1. when you scale/rotate/scroll during the pinch gesture, the pixel in the middle of your 2 fingers of course moves, but must match the same initial geo coordinates; therefore you must apply additional offsets to the Projection

**Comment by monsieurtanuki** [comment]
I hope this is the final version. I fixed everything I wanted to fix. But I guess you guys will find bugs.

Btw I forgot to add my push comments; here they are:
Impacted classes:
* `BoundingBox`: added a `set` method because coordinates are not `final` anymore
* `MapController`: adapted the code to the new "MultiTouchScale" `MapView` methods; fixed a bug in `zoomInFixing`; gently refactored
* `MapView`: refactored the "MultiTouchScale" members (renamed `mMultiTouchScaleInitPoint` and created `mMultiTouchScaleGeoPoint` and `mMultiTouchScaleCurrentPoint`); adjusted the `Projection` in `getProjection`; moved bounding box code to `Projection`; adapted pinch gesture methods `getPositionAndScale`, `setPositionAndScale` and `selectObject`; created methods `resetMultiTouchScale`, `setMultiTouchScaleInitPoint` and `setMultiTouchScaleCurrentPoint` in order to manage the MultiTouchScale history; gently refactored
* `Projection`: enabled on-the-fly adjustments by setting members (`mOffsetX`, `mOffsetY`) as non `final` anymore; removed now useless member `mScaleMatrix` and useles method `scalePoint`; removed MultiTouchScalePoint from constructor; added method `refresh` in order to take into account the possible adjutments; created an `adjustOffsets` method dedicated to ensuring that a given `GeoPoint` projects into a given pixel; moved code from `MapView` dedicated to ensuring that the `MapView` respects a given bounding box

**Comment by monsieurtanuki** [comment]
Still little things to fix, as the code doesn't pass the unit tests...

**Comment by monsieurtanuki** [comment]
@spyhunter99 I believe there's something to fix in the travis process: could you please have a look at it?
Seems to be a problem too for @secaw's #804.

**Comment by spyhunter99** [comment]
Travis is a vm with avd in it.  Unfortunately none of the x86 avds will work and the arm avds are slow and often unresponsive in this environment the fix is to just restart the jobs

**Comment by spyhunter99** [comment]
Just pulled this branch and hit a test failure

```

org.osmdroid.views.OpenStreetMapViewTest > test_toMapPixels_0_0[Custom Phone - 6.0.0 - API 23 - 768x1280 - 6.0] FAILED
        junit.framework.AssertionFailedError: the computed center of the map is in the pixel center of the map (Y)(zoom=0.09663273555239438,center=-44.75279291077021,-92.54294906214929,0.0) expected:<568.0> but was:<18.0>
        at junit.framework.Assert.fail(Assert.java:50)
                                                         :OpenStreetMapViewer:connectedDebugAndroidTest FAILED

```

**Comment by monsieurtanuki** [comment]
@spyhunter99 Very strange...
I just added the following line to `OpenStreetMapViewTest.test_toMapPixels_0_0()`, and the test passed:
````java
checkCenter(0.09663273555239438, new GeoPoint(-44.75279291077021,-92.54294906214929));
````
Could you please check that you included commit [37cb615](https://github.com/osmdroid/osmdroid/pull/800/commits/37cb6151c67ab8a0a3a0383f643e2e5809955198) in your pull?

**Comment by spyhunter99** [comment]
@monsieurtanuki i'm getting the same failure, intermittently on master so probably not related

**Comment by monsieurtanuki** [comment]
@spyhunter99 thanks for the merge!

**Pull request merged**
