### PR TITLE
Bug/#680

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Fix for bug #680 that includes a step for #329. Because I'm VERY clumsy with git. The #329 part is safe to PR.

### CODE REVIEW

**Comment by spyhunter99** [comment]
not sure what the relation is to #329 which is discussing zoom levels. The solution for that is to ditch android view scroller and maintain our own pixel x,y offsets of the world. I'm fix with the change, but it's only tangentially related to the zoom issue

**Comment by monsieurtanuki** [comment]
@spyhunter99 there's definitely no connection between #329 and #680. The thing is that I was working on #329 yesterday, spotted #680 this morning and decided to quickly fix it. The initial idea was to start from scratch for #680. And when I saw that the #329 step was included too in the PR, my first reaction as an adult was to yell. Then I failed to have a clean #680-only PR. What I committed in #329 is atomic, works and fixes another bug.

**Comment by spyhunter99** [comment]
haha no worries

**Comment by secaw** [comment]
@spyhunter99 Is it correct, that only commit 1b2af6e got merged (bug #680) and not cd618a6 (step for feature #329)?
@monsieurtanuki Does the commit cd618a6 (step for feature #329) actually repair the map rotation issue (now around map center instead of upper left corner) when tilting the device? This has been bugging me for some time now too and I was happy that you seemed to do something about it and eager to test, but no change probably due to not having been merged..?

**Comment by monsieurtanuki** [comment]
@secaw That's partially correct: the specified commit [cd618a6](https://github.com/osmdroid/osmdroid/commit/cd618a6251498fea4d3493c780373b14fd60b133) repairs the map rotation issue, but only in the `StarterMapActivity` demo. If you want to test it in another activity, you need to add some code, basically:
* save the map center latitude and longitude in prefs inside `onPause` (instead of `PREFS_SCROLL_X`) (I recommend using `OpenStreetMapConstants.PREFS_LATITUDE_STRING` and storing as a `String`, because `double` cannot be saved in prefs and `float` are not accurate enough)
* load the map center latitude and longitude from prefs inside `onActivityCreated`, and call new method `MapView.setInitCenter`

The commit is safe to merge btw. But it was very remotely connected to #680, and not even that close to #329 either!

**Comment by secaw** [comment]
@monsieurtanuki Thanks for clarification and the proposal. Unfortunately I'm overriding orientation config changes in my map activity, so I can't do it that way, but I get the idea - will figure it out. I migrated from Google maps V1 which rotated around the map center automatically..

**Comment by spyhunter99** [comment]
@secaw i'm not sure, i merged all the open PRs. If https://github.com/osmdroid/osmdroid/commit/cd618a6251498fea4d3493c780373b14fd60b133 wasn't on a PR it probably wasn't merged.

Related: there was a related branch for ticket #155 that someone opened a PR for. Unfortunately there was no sample code. Basically the idea was to offset my location to be closer towards on the bottom of the screen and still support heading/course up on the map. It only partially worked and was never merged.

**Comment by secaw** [comment]
@monsieurtanuki @spyhunter99 
Got it! This little trick with the new `MapView.setInitCenter` does it for me. Rotates nicely around the map center - perfect!

```
@Override
public void onConfigurationChanged(Configuration newConfig) {
  super.onConfigurationChanged(newConfig);
  if(newConfig.orientation != map_orientation) {
    map_orientation = newConfig.orientation;
    mapView.setInitCenter(mapView.getMapCenter());
  }
}
```

**Pull request merged**
