### PR TITLE
add GroundOverlay2

### PR DESCRIPTION
**Pull request by pasniak**
This is a first cut, it works better than GroundOverlay (with midpoint) from the bonuspack.

### CODE REVIEW

**Comment by spyhunter99** [comment]
sounds good, i'll test it later today and whip up a sample. Do you have any relevant test images that can be used for demo/testing purposes? maybe we can find a weather image to use

**Comment by spyhunter99** [comment]
I found this, https://radar.weather.gov/Conus/RadarImg/latest_Small.gif and was able to rig up a sample using it. Looking pretty good! Seems fast enough. Hard part was guessing the correct (or close enough) coordinates

image

**Comment by pasniak** [comment]
that was fast :) it would be great to have some tool to find coordinates by choosing online image location and dragging corners in place...

**Comment by spyhunter99** [comment]
good idea, this could probably be done with a four draggable markers,

**Pull request merged**
