### PR TITLE
Implemented Animated Zoom To ZoomLevel

### PR DESCRIPTION
**Pull request by johnnynotsolucky**
Added an animated zoomTo() method as well as implemented it in the zoomToBoundingBox() by providing an animate flag.

The existing zoomIn() and zoomOut() methods call the new zoomToFixing() method.

Additionally, the ZoomAnimatorListener was renamed and now includes the @TargetApi() annotation which is required due to the listener only being available in a newer API.

### CODE REVIEW

**Comment by spyhunter99** [comment]
Awesome! would it be possible to add an example on the sample app?

**Comment by spyhunter99** [comment]
This doesn't compile. Please make sure you build the entire project using maven. We don't have a 100% conversion to gradle at the moment and thus there's a lot still using maven

osmdroid-android/src/main/java/org/osmdroid/views/MapController.java:[431,84] error: inconvertible types

osmdroid-third-party/src/main/java/org/osmdroid/google/wrapper/MapController.java:[14,7] error: MapController is not abstract and does not override abstract method zoomToFixing(int,int,int) in IMapController

**Comment by tyronetudehope** [comment]
My bad, I didn't think to build all the modules.

I added `Animated Zoom to Location` sample to the samples list, which simply zooms to the the user's current location when the marker is tapped.

**Comment by spyhunter99** [comment]
cool. i like.

**Comment by spyhunter99** [comment]
thanks for the contribution!

**Pull request merged**
