### PR TITLE
feature/#1412: Implement setPadding for CustomZoomButtonsDisplay

### PR DESCRIPTION
**Pull request by wharnisch**
feature/#1412

### CODE REVIEW

**Comment by wharnisch** [comment]
Class _GoogleMaps_ in Google Maps API offers a method _setPadding_ with exactly the same parameters and functionality as the method I suggested. The 'object' is the whole view of CustomZoomButtonsDisplay, so the padding is inside the object. Therefore I thought _setPadding_ would be a suitable name for the method. Nevertheless I will try to change things like you commented.

**Comment by monsieurtanuki** [comment]
Let me have a look at the GoogleMaps' `setPadding` method.
That would make sense to match GoogleMaps method name. Assuming they're right ;)
But anyway in the current code the margin and the padding have another meaning, and we need to have consistent names. I'll get back to you.

**Comment by monsieurtanuki** [comment]
I confirm I'm right: in Google Maps, [`setPadding`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setPadding(int,%20int,%20int,%20int)) applies to a **map** and indicates the "authorized rectangle" of the map. And then, all the controls need to be in this zone, which would in your case move the zoom controls. That's what you initially wanted to do, moving the zoom controls, fair enough.

But in osmdroid, we're dealing with a method for the **zoom controls**, not for the **map** in general. Therefore in our case it's more `zoomDisplay.setMargins`.
It would be `mapView.setPaddings` if we implemented in the same spirit as GoogleMaps ("which is the authorized zone for the controls of the map?"). That would make sense too, but it's not what you've been implementing.

**Comment by wharnisch** [comment]
Sorry, did not manage to change pull request, created a new pull request (Implement setAdditionalPixelMargins for CustomZoomButtonsDisplay #1426)

**Comment by monsieurtanuki** [comment]
@wharnisch No problem, I know how git can be confusing and stressful. I learned it the hard way. Still learning btw ;)

**Pull request closed without merging**
