### PR TITLE
Optimized the display for `Polyline`

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Here are the improvements:
* for `Polyline` we now use `Canvas.drawLine` and we don't care about invisible segments: they may have an impact on visible Path but never on visible segments
* introduction of `ListPointL` as an optimization of `List<PointL>`, which is supposed to benefit both `Polyline` and `Polygon` display

New classes:
* `ListPointL`: an optimized version of `List<PointL>`
* `ListPointLTest`: a unit test class for `ListPointL`

Impacted classes:
* `LinearRing`: used new class `ListPointL` for constantly refreshed `List<PointL>`; handled the case where `mPath` is `null`; refactored a little
* `PathBuilder`: handled the case where `mPath` is `null`
* `Polyline`: removed the `Path` and handled the display with `Canvas.drawLine`
* `SegmentClipper`: added `boolean mPathMode`, to be set to `true` when dealing with a `Path` (if so we keep the invisible segments: they have an impact on Path inner area)

### CODE REVIEW

**Comment by monsieurtanuki** [comment]
@shiroyagi Could you please check if you have decent performances on polylines with this PR's optimizations?

**Comment by shiroyagi** [comment]
With 3 points the performance is now similar to 5.6.6 however with 2k points it is still not good.  Also calling clearPath() does not clear the path but freezes it relative to the viewport.

**Comment by monsieurtanuki** [comment]
...working on the subject...
As Path looks slower than drawLines, I'm going to develop a drastically different version for Polyline. There is a lot of code dedicated to offset: for Polygon holes and multiworld issues; I'll optimize it for Polyline.
I'll fix #835 too in the process.

**Comment by monsieurtanuki** [comment]
I'm very optimistic. It will be OK by the end of the week.

**Comment by monsieurtanuki** [comment]
@shiroyagi Now there's a specific optimized code for `Polyline`s. I hope it's fast enough for your needs: could you have a look at the performances?

The `Polygon`s are still slow with the hardware acceleration on, but that should rather be dealt in #820. I guess the idea would be to create a demo without `MapView`, just to infirm/confirm that dozens of `Path` cannot be displayed with decent performance, regardless of the osmdroid context.

**Comment by monsieurtanuki** [comment]
@spyhunter99 I guess I just fixed #835 in this latest commit. Could you have a look at it?

**Comment by shiroyagi** [comment]
Yes, this is much better thanks.  It is still not quite as good as 5.6.6 which was comfortably below the 60fps green line target in the GPU profiler.  It is now around and occasionally above this line (perhaps 30-50% slower and less consistent).  The proportion of update/execute rendering is roughly the same so the cause is not immediately obvious.  Could it be the clipping is constantly changing the list of lines passed whereas before it could be cached on the GPU?

**Comment by shiroyagi** [comment]
With 4k points the height of the profiler's blue 'update' bars increases and the red 'execute' bars decrease as you zoom in until the chart is nearly all blue.   This is consistent with more time spent clipping but less being drawn .  Unfortunately the total height increases, but maybe with less frequent clipping performance could actually be better than 5.6.6?

**Comment by monsieurtanuki** [comment]
I just had a look at the previous Polyline code:
* memory is more used nowadays, because int E6 coordinates and Point pixels used to be used, but it's not possible anymore (due to zoom 29) and we use now double and PointL. More intensive memory use may explain as side effect the random performance you now experience
* drawLines used to be called by chunk of 64 segments, but I use only one call of drawLines with a large float array. I can switch back to those more numerous calls of smaller arrays.

Of course, what I say only make sense if you have many many points and many many visible segments in your current performance test. Is that the case?

**Comment by monsieurtanuki** [comment]
It also looks like there used to be the minimum of home made clipping, and that the actual clipping was taken into account by drawLines.

**Comment by shiroyagi** [comment]
> drawLines used to be called by chunk of 64 segments

I only did that to keep the buffer reasonably small without impacting performance, it shouldn't actually be faster.

> the actual clipping was taken into account by drawLines.

ie. done in hardware when enabled?  This may be significantly more efficient (but problematic at zoom >=25).

**Comment by spyhunter99** [comment]
@monsieurtanuki re: the map repetition bug#835, it's fixed for vertical panning but not horiztonal

**Comment by monsieurtanuki** [comment]
@shiroyagi Just pushed my latest fixes: less clipping computation and less memory used during drawing.
Closer to the "original" fast code 6 months ago.

@spyhunter99 To me the demo "Draw a polyline on screen" works as expected: each polyline is drawn so that its center is as close to the screen center as possible (worldmapreplicationwise). I mean, I double-checked horizontally and vertically. What's the problem?
* this business rule is not what you expect
* it's not what you see

**Comment by spyhunter99** [comment]
@monsieurtanuki appears to be fixed now

**Comment by shiroyagi** [comment]
Great, that's fixed.  Same performance as before.

**Pull request merged**
