### PR TITLE
New Extra Samples Activity

### PR DESCRIPTION
**Pull request by ZKjellberg**
Created a new Extra Samples Activity to allow better discovery of the set of Fragment Examples.

Refactored the names of many files to better depict their purpose.

### CODE REVIEW

**Comment by spyhunter99** [comment]
@ZKjellberg can you fix the merge issues?

**Comment by ZKjellberg** [comment]
Will resolve shortly.

**Comment by ZKjellberg** [comment]
Merged and resolved conflicts.

**Comment by spyhunter99** [comment]
Thanks Zach!

**Comment by spyhunter99** [comment]
for reference, make sure you run the integration tests with 'mvn clean install'. we're currently broken

**Pull request merged**
