### PR TITLE
#146 removing sfl4j and using aar as the output

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by spyhunter99** [comment]
fixed

**Comment by spyhunter99** [comment]
ping, i did the work. is there a reason this hasn't been merged?

**Comment by neilboyd** [comment]
Maybe I have a little time next week for some osmdroid maintenance

**Comment by spyhunter99** [comment]
yay! If you want help or were considering passing the torch, I'm more than
willing

**Comment by neilboyd** [comment]
I added you as a collaborator so that you can make the change yourself :)

**Pull request merged**
