### PR TITLE
Temp/modernize

### PR DESCRIPTION
**Pull request by neilboyd**
This is a temporary PR to see how the GitHub Actions would look like in this repo.
The real PR is #1594.

### CODE REVIEW

**Comment by hannesa2** [comment]
Yes, this an addition way how to demonstrate 👍 
Previously I did it here https://github.com/hannesa2/osmdroid/pull/1

**Comment by hannesa2** [comment]
I see action are enabled now ! Same in https://github.com/osmdroid/osmdroid/pull/1594

**Comment by neilboyd** [comment]
> Yes, this an addition way how to demonstrate 👍
> Previously I did it here [hannesa2#1](https://github.com/hannesa2/osmdroid/pull/1)

Yes, but I wanted to demonstrate in this repo

**Comment by hannesa2** [comment]
I guess, you can close this one, because the origin builds as well

**Pull request closed without merging**
