### PR TITLE
added triming factor to setTilesScaledToDpi

### PR DESCRIPTION
**Pull request by roman-nevr**
added method setTilesScaledToDpi(float trimFactor)

### CODE REVIEW

**Comment by spyhunter99** [comment]
@roman-nevr thanks for the PR. Can you explain this a bit more? I'm not sure what's going on here nor do i understand why the change was needed

**Comment by spyhunter99** [comment]
oh and compile failed. you did compile it right? :)

````
:osmdroid-android:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/travis/build/osmdroid/osmdroid/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java:197: error: method updateTileSizeForDensity in class MapView cannot be applied to given types;
		updateTileSizeForDensity(mTileProvider.getTileSource());
		^
  required: ITileSource,float
  found: ITileSource
  reason: actual and formal argument lists differ in length
/home/travis/build/osmdroid/osmdroid/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java:402: error: method updateTileSizeForDensity in class MapView cannot be applied to given types;
		updateTileSizeForDensity(aTileSource);
		^
  required: ITileSource,float
  found: ITileSource
  reason: actual and formal argument lists differ in length
/home/travis/build/osmdroid/osmdroid/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java:1553: error: method updateTileSizeForDensity in class MapView cannot be applied to given types;
		updateTileSizeForDensity(mTileProvider.getTileSource());
		^
  required: ITileSource,float
  found: ITileSource
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/osmdroid/osmdroid/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MBTilesFileArchive.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:osmdroid-android:compileReleaseJavaWithJavac FAILED
````

**Comment by secaw** [comment]
@spyhunter99 I think, this is a great feature, allowing you to fine tune the actual individual resolution of your map, depending on the used map and needed details / readability (font sizes, etc.) especially with the new floating point zoom, where maps are getting pixelated when zooming out. This feature was actually also proposed by @monsieurtanuki in relation to the floating point zoom discussion somewhere down in #640

**Comment by monsieurtanuki** [comment]
Indeed: it makes sense to whoever is not happy with the way the tiles look x1 to x1.999, with or without density.

**Comment by spyhunter99** [comment]
i'm all for this pr. unfortunately my time has been limited lately for answering issues here and working/fixing PRs. any help is appreciated

**Comment by monsieurtanuki** [comment]
A fix for the compilation issue would be to add the following code in `MapView`:
````java
private void updateTileSizeForDensity(final ITileSource aTileSource) {
	updateTileSizeForDensity(aTileSource, 1);
}
````

**Comment by spyhunter99** [comment]
i applied that fix, but it's failing due to unit test error

java.lang.AssertionError: distance between 0.0,126.213239072563,0.0 and 0.0,126.213239073563,0.0 expected:<1.113198954901672E-4> but was:<1.1131858201318678E-4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.osmdroid.util.GeoPointTest.test_distanceTo_Equator_Smaller(GeoPointTest.java:73)

**Comment by monsieurtanuki** [comment]
I guess it's a "bad luck" failure.
In this unit test 2 `GeoPoint`s are computed at random. In this very case, they are very very close, and therefore we reach the limits of the distance computation accuracy.
Therefore:
* unit tests can be run again now and should be OK, unless we're very unlucky once more
* I'll edit the unit test in order to set a minimum distance between the 2 random `GeoPoint`s / to set a minimum distance accuracy

**Comment by secaw** [comment]
@monsieurtanuki Exactly what I thought, thanks for clearing this up.

**Comment by roman-nevr** [comment]
sorry for delaying. is anybody applied fix?

`private void updateTileSizeForDensity(final ITileSource aTileSource) {
	updateTileSizeForDensity(aTileSource, 1);
}`

**Comment by monsieurtanuki** [comment]
@roman-nevr I imagine @spyhunter99 added that fix locally, but didn't go further because the unit tests crashed. The unit tests crash was not related to your code, and I fixed the unit tests. That where we are now.

I guess you can push that fix.

**Comment by spyhunter99** [comment]
retesting now

**Comment by spyhunter99** [comment]
so i merged this into a local branch and still had some test failures.

````

org.osmdroid.test.CacheAnalyzerTest > testActivity[Custom Phone - 6.0.0 - API 23 - 768x1280 - 6.0] FAILED
        java.lang.AssertionError: Values should be different. Actual: Loading stats...
        at org.junit.Assert.fail(Assert.java:88)

org.osmdroid.views.OpenStreetMapViewTest > test_toMapPixels_0_0[Custom Phone - 6.0.0 - API 23 - 768x1280 - 6.0] FAILED
        junit.framework.AssertionFailedError: the computed center of the map is in the pixel center of the map (Y) expected:<568.0> but was:<41.0>
        at junit.framework.Assert.fail(Assert.java:50)
                                                         :OpenStreetMapViewer:connectedDebugAndroidTest FAILED

````

**Comment by monsieurtanuki** [comment]
Regarding `test_toMapPixels_0_0` I guess it's another "bad luck" issue. I'll fix that this week.
Another "bad luck" issue apparently on `CacheAnalyzerTest`, but I don't know what to do about it.

**Comment by monsieurtanuki** [comment]
I managed to reproduce the `test_toMapPixels_0_0` failure, then added some verbosity in order to understand the problem, but then wasn't able to reproduce the failure again...
In addition, I just committed the "added verbosity" code, but then fell into github's rabbit's hole.
In short: not very productive today so far.

**Comment by secaw** [comment]
Could we give this another try? Really think, it would be useful...

**Comment by secaw** [comment]
OK, looking at the logs and code again there ARE actual code errors, it's not working that way. `updateTileSizeForDensity(final ITileSource aTileSource)` is missing now and we also need a new var, something like `mTilesScaledToDpiTrimFactor` in order to make it work properly. I can fix it, should I do a new PR on this?

**Pull request closed without merging**
