### PR TITLE
"Polylines with arrows": introduced bitmaps as milestone display and several milestone recurrence schemes, with a bit of refactoring

### PR DESCRIPTION
**Pull request by monsieurtanuki**
"Polylines with arrows": introduced `Bitmap`s as milestone display and several milestone recurrence schemes, with a bit of refactoring.

There are new concepts and new classes.

_Milestone step_:
* `MilestoneStep`: pixel position where a milestone should be displayed with an orientation

_Milestone lister_:
* `MilestoneLister`: creating a list of `MilestoneStep`s (abstract)
* `MilestoneMiddleLister`: creating a list of `MilestoneStep`s with the middle of each segments
* `MilestonePixelDistanceLister`: creating a list of `MilestoneStep`s every x pixels on the `Path`
* `MilestoneVertexLister`: creating a list of `MilestoneStep`s with each vertex
* `MilestoneListerTest`: checking that we compute correct orientations for `MilestoneStep`s

_Milestone displayer_:
* `MilestoneDisplayer`: displaying `MilestoneStep`s (abstract)
* `MilestoneBitmapDisplayer`: displaying `MilestoneStep`s as `Bitmap`s
* `MilestonePathDisplayer`: displaying `MilestoneStep`s as `Path`s

_Milestone manager_:
* `MilestoneManager`: handling the list of `MilestoneStep`s (through a `MilestoneLister`) and their display (through a `MilestoneDisplayer`)

Other new classes:
* `DrawPolygonWithArrows`: same as `DrawPolylineWithArrows` but for `Polygon`s
* `PathBuilder`: was initially code from `SegmentClipper`
* `PointAccepter`: used to be something like `SegmentClipper.SegmentClippable`

Removed classes:
* `ArrowsLinearRing`: moved code to `LinearRing` and more flexible `MilestoneManager`

Impacted classes:
* `SampleFactory`: added new class `DrawPolygonWithArrows`
* `CustomPaintingSurface`: used the new "arrows" syntax for both `Polyline` and `Polygon`; removed dead code
* `SegmentClipper`: implemented `PointAccepter`; went from constructor and `final` methods to less memory consuming setter; went from `RectL` as segments to a list of coordinates as parameters
* `LinearRing`: went from `RectL` as segments to `PointL`s in order to save memory
* `Polygon`: introduced the concept of `MilestoneManager`
* `Polyline`: introduced the concept of `MilestoneManager`
* `SegmentClipperTest`: used the new `SegmentClipper.set` and `SegmentClipper.clip` syntaxes

### CODE REVIEW

**Comment by spyhunter99** [comment]
image

for draw polyline with arrows, i get the following output. I'm not entirely sure what the logic is, but sometimes i get a 1 arrow, some get none, some get more than one. Is this expected?

Polygon with arrows is pretty neat, although i'm not sure what the use case is for it

image

**Comment by monsieurtanuki** [comment]
What is displayed on your screenshots reflects what is expected to happen in method `CustomPaintingSurface.touch_up`.

For `Polyline`:
* we create a simple `Path` (an triangular arrow towards the right) in order to display milestones - _cf._ `MilestonePathDisplayer`
* we will add a milestone in the middle of every `Polyline`'s segment, provided that it's at least 50 pixel long - _cf._ `MilestoneMiddleLister`
````java
final Path path = new Path();
path.moveTo(- 10, - 10);
path.lineTo(10, 0);
path.lineTo(- 10, 10);
path.close();
line.setMilestoneManager(new MilestoneManager(
		new MilestoneMiddleLister(50),
		new MilestonePathDisplayer(0, true, path, paint)
));
````

For `Polygon`:
* we use a `Bitmap` in order to display milestones - _cf._ `MilestoneBitmapDisplayer`
* we will add a milestone every 200 pixels starting at pixel 12 - _cf._ `MilestonePixelDistanceLister`
````java
final Bitmap bitmap = BitmapFactory.decodeResource(getResources(), org.osmdroid.library.R.drawable.direction_arrow);
polygon.setMilestoneManager(new MilestoneManager(
		new MilestonePixelDistanceLister(12, 200),
		new MilestoneBitmapDisplayer(90, true, bitmap, bitmap.getWidth() / 2, bitmap.getHeight() / 2)
));
````
What's the use case for `Polygon`s? I don't know, anticyclone (with arrows), forbidden areas (with no-entry signs), whatever.

I'm open to suggestions of better examples regarding polyline "arrows" demo, polygon "arrows" demo, `MilestoneLister` and `MilestoneDisplayer`.

**Comment by spyhunter99** [comment]
`we will add a milestone in the middle of every Polyline's segment, provided that it's at least 50 pixel long`

I believe that quite a few of those are more than 50 pixels and do not have the milestone

**Comment by monsieurtanuki** [comment]
> I believe that quite a few of those are more than 50 pixels and do not have the milestone

Ha ha, that's what you think! ;)
When you draw your polyline in the demo, it's split in numerous segments, many of them not longer than 50 pixels.
I just added the following feature: being able to use multiple `MilestoneManager`s on `Polyline` and `Polygon`. And in the "polyline with arrows" demo, I added a red cross at each vertex.
device-2017-12-28-103925
Does it work? Yes. Is that beautiful? Definitely not. Therefore we need to think about better examples.

**Comment by monsieurtanuki** [comment]
I'm about to implement 2 new polyline demos:
* a weather one, with anticyclones
* a running one, something like Paris marathon. For that one I'll develop new features in milestones - meter distance and item number.

Still thinking about the ultimate polygon with arrows demo. Maybe polluted areas.

**Comment by monsieurtanuki** [comment]
> something like Paris marathon. For that one I'll develop new features in milestones - meter distance and item number.

I'm lazy, I just developed a 10k race instead of a marathon. But the meter distance computation works ok (just compare to the [original map](http://www.10km.lequipe.fr/fr/infos-pratiques/parcours-et-profils))
device-2017-12-28-194543

**Comment by spyhunter99** [comment]
@monsieurtanuki ready for merge?

**Comment by monsieurtanuki** [comment]
Ready for merge, as long as it's ok for you too.

**Pull request merged**
