### PR TITLE
bug/#1145 - using the new DirectRenderer class of mapsforge

### PR DESCRIPTION
**Pull request by monsieurtanuki**
That fixes the issue.

Not to be merged as is, because we still rely on a `SNAPSHOT` version of `mapsforge`.
As soon as `mapsforge` issues a new version, the `build.gradle` file must be edited and marginally also a comment in `MapsForgeTileSource` about the `mapsforge` version number.

Impacted files
* `osmdroid-mapsforge/build.gradle`: now using the latest version of `mapsforge`, that includes the new `DirectRenderer` class that I coded in `mapsforge`
* `MapsForgeTileSource`: used `DirectRenderer` instead of `DatabaseRenderer`

### CODE REVIEW

**Comment by monsieurtanuki** [comment]
In this version (not to be merged until MapsForge's new version is released):
* the "out-of-box tile returns NULL" feature is implemented (cf. @secaw)
* the labels are never broken anymore - I mean - they still are but are immediately refreshed whenever needed

@secaw I finally left the `TileWriter` as it was. Still, there's confusion with MapsForge being used and its tiles being computed then stored into a `TileWriter`:
1. the data is stored twice
1. the labels cannot be consistent as there's no such thing as definite MapsForge displayed labels for a tile (the display depends on the order in which the other tiles were sequentially displayed)

**Comment by monsieurtanuki** [comment]
@spyhunter99 It looks like the new mapsforge version (0.11.0) has been released.
I don't know if you plan to include this osmdroid PR into the next osmdroid release.

**Comment by spyhunter99** [comment]
i made a quick fix, however it is crashing for me....

ader.nextTile() on provider: MapsforgeTiles Provider found tile in working queue: /3/3/4
            TileLoader.nextTile() on provider: MapsforgeTiles Provider adding tile to working queue: 864691130065747972
            TileLoader.run() processing next tile: /3/3/4, pending:1, working:1
            MapsForgeTileModuleProvider.TileLoader.loadTile(/3/3/4): tileSource.renderTile
W/System.err:     at org.osmdroid.util.BoundingBox.set(BoundingBox.java:67)
                  at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
                  at org.osmdroid.mapsforge.MapsForgeTileSource.getBoundsOsmdroid(MapsForgeTileSource.java:109)
                  at org.osmdroid.samplefragments.tileproviders.OfflinePickerSample$3$1$1.run(OfflinePickerSample.java:299)
                  at android.os.Handler.handleCallback(Handler.java:739)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:158)
                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                  at java.lang.reflect.Method.invoke(Native Method)
W/DirectRenderer: Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.app.Application.getAssets()' on a null object reference
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
D/OsmDroid: TileLoader.tileLoadedFailed() on provider: MapsforgeTiles Provider with tile: /3/3/4


probably missing as asset but i have no clue what

**Comment by monsieurtanuki** [comment]
@spyhunter99 I ran my tests with the file provided in #1145. Which mapsforge .map file are you using? Would you be able to share it?

**Comment by monsieurtanuki** [comment]
@spyhunter99 Hmm, I guess the file is world.map in the root of the git project.

**Comment by monsieurtanuki** [comment]
@spyhunter99 This is what I've just done:
* I copied the `world.map` file from my desktop osmdroid github root folder to my smartphone in `/osmdroid`
* I ran the demo: "More Samples / Mapsforge tiles" on my 1145 branch
* It crashed because of the tile bounds, which explained your fix merge
* I copied your fix code into mine, and still had the `java.lang.IllegalArgumentException: north must be in [-85.05112877980659,85.05112877980659]` crash
* because the correct fix is:
````java
double latNorth= Math.min(MapView.getTileSystem().getMaxLatitude(),boundingBox.maxLatitude);
double latSouth= Math.max(MapView.getTileSystem().getMinLatitude(),boundingBox.minLatitude);
````
* with that, the demo works like a charm, even on the Antarctica / Arctic junction (btw I never noticed before that Tierra de Fuego is kind of reflected on the Antarctica side)

**Comment by monsieurtanuki** [comment]
@spyhunter99 I've just pushed the fix.

**Comment by spyhunter99** [comment]
just tested it, after a good old clean and build, its working! good job

**Pull request merged**
