### PR TITLE
Overlay for fast drawing hundred thousand points

### PR DESCRIPTION
**Pull request by miguel-porto**
Added SimpleFastPointOverlay, optimized for drawing speed. Only draws points with basic styling, and optionally with labels. Good performance up to 100k points, but usable even with 1M points. Has three rendering engines, which differ on performance.
Also added a sample to the sample app.
I had to create a new callback event passed to all overlays (onExtentChange), which is fired whenever the MapListener is called (i.e. after a zoom animation finishes, or after a scroll event). Hope it's ok to include this event.
May have bugs, but for a first version I think it's fairly functional.
Best,
Miguel

### CODE REVIEW

**Comment by spyhunter99** [comment]
merge conflicts

**Comment by spyhunter99** [comment]
isn't the onDraw event good enough for onExtentChange?

**Comment by miguel-porto** [comment]
You're right! Sorry!! Removed it completely. Basically I needed to call a method only after animations or after touchup, but I forgot I could just check the isAnimating()!

**Comment by miguel-porto** [comment]
Hmm... I guess the last failed check is something that needs to be fixed from your side, right?

**Comment by spyhunter99** [comment]
i'll check it out locally to see what the deal is

**Comment by spyhunter99** [comment]
saw this one, doesn't look like its your code though

```
11-14 18:48:25.832 21355 21355 D StatusBar.NetworkController: applyTMO
11-14 18:48:25.902  2705  2737 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.osmdroid.views.MapView.getZoomLevel()' on a null object reference
11-14 18:48:25.922  2705  2737 W System.err:    at org.osmdroid.samplefragments.data.SampleOsmPath.runTestProcedures(SampleOsmPath.java:225)
11-14 18:48:25.922  2705  2737 W System.err:    at org.osmdroid.test.ExtraSamplesTest.executeTest(ExtraSamplesTest.java:113)
11-14 18:48:25.922  2705  2737 W System.err:    at org.osmdroid.test.ExtraSamplesTest.testActivity(ExtraSamplesTest.java:43)
11-14 18:48:25.922  2705  2737 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-14 18:48:25.922  2705  2737 W System.err:    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
11-14 18:48:25.922  2705  2737 W System.err:    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
11-14 18:48:25.922  2705  2737 W System.err:    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
11-14 18:48:25.922  2705  2737 W System.err:    at junit.framework.TestCase.runBare(TestCase.java:134)
```

**Comment by spyhunter99** [comment]
this looks to be the root cause
````
11-14 18:57:41.822  7715  7715 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.api.IMapController org.osmdroid.views.MapView.getController()' on a null object reference
11-14 18:57:41.822  7715  7715 W System.err:    at org.osmdroid.samplefragments.data.SampleSimpleFastPointOverlay$2.run(SampleSimpleFastPointOverlay.java:81)
11-14 18:57:41.822  7715  7715 W System.err:    at android.os.Handler.handleCallback(Handler.java:739)
11-14 18:57:41.822  7715  7715 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 18:57:41.822  7715  7715 W System.err:    at android.os.Looper.loop(Looper.java:158)
11-14 18:57:41.822  7715  7715 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7224)
11-14 18:57:41.822  7715  7715 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-14 18:57:41.822  7715  7715 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
11-14 18:57:41.822  7715  7715 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
````

**Comment by miguel-porto** [comment]
Thanks! I'll fix this, this error was not happening in my local project...

**Comment by spyhunter99** [comment]
super exciting by the way! I think the NPE is just due to how we run the connectedCheck tests.. Just add a quick null check in there. Once it's merged, I can work on the test code to ensure that it's exercised.

Performance at higher zoom levels (higher numerical) is great. When zoomed out, performance is still pretty good on my S5. Fantastic work!

I've also noticed that text labels appear sometimes, but other times it does not at the same zoom level. Not sure what's up with that

One final note, the clipping bounds does not appear to take map rotation/orientation into account, which is fine, as long as it's documented somewhere in the javadoc.

**Comment by miguel-porto** [comment]
Thanks for the nice comments!
I added a null check, hope it works now. I also improved some performance issues.
Yes, the label behaviour you mention is expected, but I agree it's not very elegant. So I added a LabelPolicy option now. The default now is to hide labels below a given zoom level, which is more consistent. But I kept the previous option also, of only showing labels when the number of points in viewable area is less than N - this in fact makes labels appear or disappear in the same zoom level, but it's useful in some cases to avoid cluttering.
I tried to solve the rotation issue but I confess I was not able to find a simple way to get the corner coordinates of the screen in a rotated map... so I left it with the issue, and wrote a line in the JDoc. But I shall try to solve this in the future.
Best!
Miguel

**Comment by spyhunter99** [comment]
looks like there may be some memory issues at with the new code or it's possible that just it just needs too much memory for an api19 emulator. We can probably skip running that fragment for api10 devices if needed or maybe reduce the number of points for that test. It could also be a memory leak. thoughts?

**Comment by spyhunter99** [comment]
@miguel-porto are we ready to merge yet?

**Comment by miguel-porto** [comment]
Oh, you solved the failed tests! I could not really understand what was going on, they seemed to fail sometimes, other times not. Anyway, I didn't find any reference to my code in the exceptions.
Maybe I'll revert the sample back to 100k points, to better show the potential, before merging? What do you think?

**Comment by spyhunter99** [comment]
travis runs a build matrix, which has a 30% chance of failing due to travis infra issues, avd, or random gradle problems.

**Comment by miguel-porto** [comment]
Hum... but then how can I do something to overcome this?

**Comment by spyhunter99** [comment]
click on details above, then restart each job that failed.

**Comment by miguel-porto** [comment]
I guess that's just available for the repo owners!
Thanks

**Comment by miguel-porto** [comment]
Let's see now! Sorry for bouncing back and forth, thanks.

**Comment by spyhunter99** [comment]
merged!

**Comment by miguel-porto** [comment]
Thanks!
Still find strange all these "random" failed checks.
All the best,

**Comment by spyhunter99** [comment]
travis is basically docker/aws which runs android virtual devices to run the tests. It's a ARM emulated VM in a VM. Things frequently fail due to avd issues, virtualization, etc. It's usually been a 20% false failure rate, but what do you want for nothing

**Comment by pasniak** [comment]
I'd like to use SimpleFastPointOverlay but vary labels' colors and point colors.  Is my only option to override draw?
```
public class SimpleFastPointOverlay extends Overlay { 
...
    public void draw(Canvas canvas, MapView mapView, boolean b) {
```
Maybe it would be better to refactor parts of draw into a protected method so I can override it?

```
NO_OPTIMIZATION:
                               if(this.mStyle.mSymbol == Shape.CIRCLE) {
                                    canvas.drawCircle((float)this.grid[x][y].x + offX - this.offsetX, (float)this.grid[x][y].y + offY - this.offsetY, this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                                } else {
                                    canvas.drawRect((float)this.grid[x][y].x + offX - this.offsetX - this.mStyle.mCircleRadius, (float)this.grid[x][y].y + offY - this.offsetY - this.mStyle.mCircleRadius, (float)this.grid[x][y].x + offX - this.offsetX + this.mStyle.mCircleRadius, (float)this.grid[x][y].y + offY - this.offsetY + this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                                }

                                if(this.mPointList.isLabelled() && showLabels && (tmpLabel = this.grid[x][y].mlabel) != null) {
                                    canvas.drawText(tmpLabel, (float)this.grid[x][y].x + offX - this.offsetX, (float)this.grid[x][y].y + offY - this.offsetY - this.mStyle.mCircleRadius - 5.0F, this.mStyle.mTextStyle);
                                }


MEDIUM_OPTIMIZATION:
                                if(this.mStyle.mSymbol == Shape.CIRCLE) {
                                    canvas.drawCircle((float)mPositionPixels.x, (float)mPositionPixels.y, this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                                } else {
                                    canvas.drawRect((float)mPositionPixels.x - this.mStyle.mCircleRadius, (float)mPositionPixels.y - this.mStyle.mCircleRadius, (float)mPositionPixels.x + this.mStyle.mCircleRadius, (float)mPositionPixels.y + this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                                }

                                if(this.mPointList.isLabelled() && showLabels && (tmpLabel = ((LabelledGeoPoint)pt1).getLabel()) != null) {
                                    canvas.drawText(tmpLabel, (float)mPositionPixels.x, (float)mPositionPixels.y - this.mStyle.mCircleRadius - 5.0F, this.mStyle.mTextStyle);
                                }

MAXIMUM_OPTIMIZATION:
                            if(this.mStyle.mSymbol == Shape.CIRCLE) {
                                canvas.drawCircle((float)mPositionPixels.x, (float)mPositionPixels.y, this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                            } else {
                                canvas.drawRect((float)mPositionPixels.x - this.mStyle.mCircleRadius, (float)mPositionPixels.y - this.mStyle.mCircleRadius, (float)mPositionPixels.x + this.mStyle.mCircleRadius, (float)mPositionPixels.y + this.mStyle.mCircleRadius, this.mStyle.mPointStyle);
                            }

                            if(this.mPointList.isLabelled() && showLabels && (tmpLabel = ((LabelledGeoPoint)pt1).getLabel()) != null) {
                                canvas.drawText(tmpLabel, (float)mPositionPixels.x, (float)mPositionPixels.y - this.mStyle.mCircleRadius - 5.0F, this.mStyle.mTextStyle);
                            }
```

**Comment by miguel-porto** [comment]
Individual styling would be a nice feature to integrate in SimpleFastPointOverlay. I'm working on it already, thanks for the idea.
But I'll try to refactor as you say, if it doesn't impact rendering speed. Rendering speed is the focus here.
Please note that the code you post is not up-to-date. That's not working very well. You'd better update to latest (don't know if it's published yet, but you can always clone master and install into local maven repo).

**Pull request merged**
